name: CaptainHook Deploy Notify
description: Post concise deploy notifications to Discord (krill-style success digest + failure alert)

inputs:
  discord-webhook-url:
    description: Discord Incoming Webhook URL
    required: true
  openai-api-key:
    description: Deprecated no-op (kept for backward compatibility)
    required: false
    default: ""
  openai-model:
    description: Deprecated no-op (kept for backward compatibility)
    required: false
    default: gpt-5-mini
  job-status:
    description: Job status from the caller (typically job.status from workflow context)
    required: false
    default: success
  style-file:
    description: Deprecated no-op (kept for backward compatibility)
    required: false
    default: ""
  max-commits:
    description: Max commit subjects to inspect
    required: false
    default: "8"

runs:
  using: composite
  steps:
    - name: CaptainHook notify
      shell: bash
      env:
        CH_DISCORD_WEBHOOK_URL: ${{ inputs.discord-webhook-url }}
        CH_OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        CH_OPENAI_MODEL: ${{ inputs.openai-model }}
        CH_JOB_STATUS: ${{ inputs.job-status }}
        CH_STYLE_FILE: ${{ inputs.style-file }}
        CH_MAX_COMMITS: ${{ inputs.max-commits }}
      run: |
        python3 "$GITHUB_ACTION_PATH/notify.py"
